#pragma checksum "..\..\App.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9A2CAA0AA6BC1419FF663DB347B41C5F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Travel_GUI;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using System.Threading;

namespace Travel_GUI
{
    
    /// <summary>
    /// App
    /// </summary>
    public class App : System.Windows.Application {
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            
            //#line 5 "..\..\App.xaml"
            //this.StartupUri = new System.Uri("MainWindow.xaml", System.UriKind.Relative);
            
            //#line default
            //#line hidden
        }

        public static MainWindow CreateMainWindow()
        {
            Thread.CurrentThread.SetApartmentState(ApartmentState.STA);
            return new Travel_GUI.MainWindow();
        }
        
        /// <summary>
        /// Application Entry Point.
        /// </summary>
        //[System.STAThreadAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public static void Main(MainWindow window)
        {
            Thread.CurrentThread.SetApartmentState(ApartmentState.STA);
            Travel_GUI.App app = new Travel_GUI.App();
            app.InitializeComponent();
            window.Activated += new EventHandler((o, e) =>
            {
                var w = (MainWindow)o;
                w.WindowState = WindowState.Maximized;
            });
            window.StateChanged += new EventHandler((o, e) =>
            {
                var w = (MainWindow)o;
                if (w.WindowState != WindowState.Minimized)
                {
                    w.WindowState = WindowState.Maximized;
                }
            });
            app.Run(window);
        }
    }
}

